#!/bin/bash

# set background image
if [[ -f $HOME/.fehbg ]]; then
	$HOME/.fehbg &
else
	feh --bg-fill --randomize $HOME/pictures/random &
fi

# dwmbar &
xsetroot -name "Arch Linux - Keep It Simple Stupid | " &
exit 0
