#!/bin/bash

# set background image
if [[ -f $HOME/.fehbg ]]; then
	$HOME/.fehbg &
else
	feh --bg-fill --randomize $HOME/pictures/random &
fi

# dwmbar &
# start a composite manager

xsetroot -name "  Arch Linux | " &
exit 0
