#!/bin/bash

# set background image
if [[ -f $HOME/.fehbg ]]; then
	~/.fehbg
else
	feh --bg-fill /usr/share/pixmaps/background.jpg
fi

# dwmbar &
xsetroot -name "Arch Linux - Keep It Simple Stupid | "
exit 0
